# -*- coding: utf-8 -*-
"""tellegram susenas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-23pZnyoenwDcC2jl78ahBnV-mLlfvAp
"""


# -*- coding: utf-8 -*-
 
import telebot
 
API_TOKEN = '1668765720:AAGxAInZvcMgaCDTEmJoi18o4p7IsQPzF8U'
bot = telebot.TeleBot(API_TOKEN)


@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
	'''Welcome message.'''
	user = message.from_user
	bot.reply_to(message, f"Assalamualaikum, haiiii Kakk  {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}. kenalin namaku Susen, aku berasal dari Sekolah Stata. kakak bisa akses di sekolahstata.com")

@bot.message_handler(regexp='mulai')
def send_welcome(message):
	'''Welcome message.'''
	user = message.from_user
	bot.reply_to(message, f"Assalamualaikum Wr Wb Kak  {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}. kenalin namaku Susen, aku berasal dari Sekolah Stata. kakak bisa akses di sekolahstata.com")

@bot.message_handler(regexp='assalamualaikum')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"Waalaikumussalam wr wb Kak  {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}.")
@bot.message_handler(regexp='salam')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"Waalaikumussalam wr wb Kak  {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}.")

@bot.message_handler(regexp='broh')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"biasakan ucapkan salam diawal ya kak {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}.")

@bot.message_handler(regexp="nanya dong")
def command_help(message):
    bot.reply_to(
        message,
        "iyahhh, silahkan tapi soal data susenas dari BPS  ya Kak, jangan yang lain"
    )
    
@bot.message_handler(regexp='mau nanya')
def command_help(message):
    bot.reply_to(
        message,
        "iyah, silahkan tapi soal data susenas dari BPS  ya Kak, jangan yang lain"
    )
    
@bot.message_handler(regexp='cuy')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"biasakan ucapkan salam diawal ya kak   {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}")
@bot.message_handler(regexp='sis')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"biasakan ucapkan salam diawal ya kak   {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}")
		 
@bot.message_handler(regexp='cuk')
def command_help(message):
    user = message.from_user
    bot.reply_to(message, f"biasakan ucapkan salam diawal ya kak   {user.first_name if user.first_name else ''} {user.last_name if user.last_name else ''}")
@bot.message_handler(regexp='apa susenas')
def command_help(message):
    bot.reply_to(
        message, "menurut BPS, Survei Sosial Ekonomi Nasionel (Susenas) merupakan salah satu sumber data sosial ekonomi rumah tangga yang penting di Indonesia. Data yang dihasilkan oleh survei ini telah banyak digunakan oleh berbagai kalangan, baik di dalam maupun di luar negeri." )

@bot.message_handler(regexp='itu susenas')
def command_help(message):
    bot.reply_to(
        message, "menurut BPS, Survei Sosial Ekonomi Nasionel (Susenas) merupakan salah satu sumber data sosial ekonomi rumah tangga yang penting di Indonesia. Data yang dihasilkan oleh survei ini telah banyak digunakan oleh berbagai kalangan, baik di dalam maupun di luar negeri." )
@bot.message_handler(regexp='susenas adalah')
def command_help(message):
    bot.reply_to(
        message, "menurut BPS, Survei Sosial Ekonomi Nasionel (Susenas) merupakan salah satu sumber data sosial ekonomi rumah tangga yang penting di Indonesia. Data yang dihasilkan oleh survei ini telah banyak digunakan oleh berbagai kalangan, baik di dalam maupun di luar negeri." )
@bot.message_handler(regexp='kapan susenas')
def command_help(message):
    bot.reply_to(
        message, "menurut BPS, Data ini dimulai pada tahun 1963" )
@bot.message_handler(regexp='pengambilan data')
def command_help(message):
    bot.reply_to(
        message, "Bulan Maret: Peruntukan untuk Penyajian hingga level Kabupaten/Kota Ukuran Sample 2015: 300.000 RumahTangga. sedangkan Bulan September Peruntukan untuk Penyajian hingga level Provinsi Ukuran Sample 2015: 75.000 RumahTangga" )

@bot.message_handler(regexp='pembobotan')
def command_help(message):
    bot.reply_to(
        message, "Sederhananya  bobot menunjukkan 1  sampel di Susenas mewakili berapa orang di Populasi. Nama variable: weind/wert atau fwt")


@bot.message_handler(regexp='pohon susenas')
def command_help(message):
    bot.reply_to(
        message, "Data KOR Cross-Section (CS) Susenas dikeluarkan setiap tahunnya. Modul dikeluarkan bergantian 3 tahunan, ex: 2008 Modul Konsumsi, 2009 Modul Sosial Budaya dan Pendidikan, 2010 Modul Kesehatan dan Perumahan. Sejak 2011, Modul Konsumsi CS dikeluarkan setiap tahunnya. Data Panel merupakan data cohort 3 tahunan, paling terakhir tahun 2011 2013" )

@bot.message_handler(
    regexp='((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)')
def command_url(message):
    bot.reply_to(message, " Maaf Kak  aku nggak bisa membuka link tersebut")


@bot.message_handler(regexp='seneng')
def command_url(message):
    bot.reply_to(
        message,
        "terima kasih Banyak yakk, jangan lupa ikuti sosial media kita yakk, follow ig ku di https://www.instagram.com/pesan_mutiara_bangsa/, website : https://pesantrenmutiarabangsa.com")


@bot.message_handler(regexp='terima kasih')
def command_url(message):
    bot.reply_to(
        message,
        "terima kasih Banyak yakk, jangan lupa ikuti sosial media kita yakk,  follow ig ku di https://www.instagram.com/pesan_mutiara_bangsa/, website : https://pesantrenmutiarabangsa.com")


@bot.message_handler(regexp='mantab')
def command_url(message):
    bot.reply_to(
        message,
        "terima kasih Banyak yakk, jangan lupa ikuti sosial media kita yakk,  follow ig ku di https://www.instagram.com/pesan_mutiara_bangsa/, website : https://pesantrenmutiarabangsa.com")

@bot.message_handler(regexp='makasih')
def command_url(message):
    bot.reply_to(
        message,
        "terima kasih Banyak yakk, jangan lupa ikuti sosial media kita yakk")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
    bot.reply_to(message, "maaf yak,   saya belum paham yang kau maksd, coba tanyakan tentang ngaji insyaallah saya bisa memberikan rekomendasi")


# and here we actually run it
bot.polling()


